run:
  timeout: "5m"
linters:
  presets:
    - performance
  enable:
    # https://golangci-lint.run/usage/linters/#enabled-by-default
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    #
    - gosec
    - gocritic
    - gosmopolitan
  disable:
    - noctx
